#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Installing frontend dependencies..."

# Required to build the frontend below
ynh_nodejs_install

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# CHANGING DEX REDIRECT_URL
#=================================================
ynh_script_progression "Changing Dex redirect url"

setup_dex

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Updating env configuration file..."

ynh_config_add --template="env" --destination="$install_dir/.env"

ynh_script_progression "Rebuilding the frontend..."

pushd "$install_dir/src/frontend"
  ynh_hide_warnings ynh_exec_as_app npm ci
  ynh_hide_warnings ynh_exec_as_app NODE_ENV=production VITE_API_BASE_URL="https://${new_domain}" npm run build -- --outDir="$install_dir/_build/frontend" --emptyOutDir
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
